# Generated by Django 2.2.5 on 2023-03-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20230308_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='photo',
        ),
    ]
