# Generated by Django 2.2.5 on 2023-03-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_remove_alumni_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(blank=True, upload_to='alumni_images'),
        ),
    ]
