# Generated by Django 2.2.5 on 2023-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20230309_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(blank=True, upload_to='./alpha_alumni/alumni_images'),
        ),
    ]
